var backgr = tryToLoad("backgr","black");
var trash = tryToLoad("trash","black");
var lake1 = tryToLoad("lake1","black");
var lake0 = tryToLoad("lake0","black");
var GCoin = tryToLoad("GCoin","black");
var most = tryToLoad("most","black");
var binn=[]
binn[0] = tryToLoad("bin[0]","black");
binn[1] = tryToLoad("bin[1]","black");
binn[2] = tryToLoad("bin[2]","black");
var Windmill = []
Windmill [0] = tryToLoad("Windmill","black");
Windmill [1] = tryToLoad("Windmill_1","black");
Windmill [2] = tryToLoad("Windmill_2","black");
var riverr = []
riverr [0] = tryToLoad("Wave_1","black");
riverr [1] = tryToLoad("Wave_2","black");
riverr [2] = tryToLoad("Wave_3","black");
var trash = []
trash[0] = tryToLoad("trash_banana","black");
trash[1] = tryToLoad("trash_coke", "black");
trash[2] = tryToLoad("trash_bottle", "black");